set_property PACKAGE_PIN V17 [get_ports {adda[0]}]
set_property PACKAGE_PIN V16 [get_ports {adda[1]}]
set_property PACKAGE_PIN W16 [get_ports {adda[2]}]
set_property PACKAGE_PIN W17 [get_ports {adda[3]}]
set_property PACKAGE_PIN W15 [get_ports {addb[0]}]
set_property PACKAGE_PIN V15 [get_ports {addb[1]}]
set_property PACKAGE_PIN W14 [get_ports {addb[2]}]
set_property PACKAGE_PIN W13 [get_ports {addb[3]}]
set_property PACKAGE_PIN U16 [get_ports {adds[0]}]
set_property PACKAGE_PIN E19 [get_ports {adds[1]}]
set_property PACKAGE_PIN U19 [get_ports {adds[2]}]
set_property PACKAGE_PIN V19 [get_ports {adds[3]}]
set_property PACKAGE_PIN W18 [get_ports {adds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adda addb adds}]
